version: '2'

services:
  
    



  squadninja-frontend:
    container_name: squadninja-frontend-container
    build: ./squadninja-frontend
    ports:
      - 4200:4200
    network_mode: "host"

  openvidu-server-kms:
    image: openvidu/openvidu-server-kms:latest
    container_name: openvidu-server-kms
    #    build: ./chat backend/docker
    ports:
      - "4443:4443"
    environment:
      - openvidu.secret=MY_SECRET
#      - openvidu.publicurl=https://localhost:4443/4443
    restart: always


    #WAIT_HOSTS: comma separated list of pairs host:port for which you want to wait.
    #WAIT_HOSTS_TIMEOUT: max number of seconds to wait for the hosts to be available before failure. The default is 30 seconds.
    #WAIT_BEFORE_HOSTS: number of seconds to wait (sleep) before start checking for the hosts availability
    #WAIT_AFTER_HOSTS: number of seconds to wait (sleep) once all the hosts are available
    #WAIT_SLEEP_INTERVAL: number of seconds to sleep between retries. The default is 1 second.



